const ERROR_CODE_INVALID = 400;
const ERROR_CODE_NOTFOUND = 404;
const ERROR_CODE_DEFAULT = 500;
const SUCCESS = 201;

module.exports = {
  ERROR_CODE_INVALID, ERROR_CODE_NOTFOUND, ERROR_CODE_DEFAULT, SUCCESS,
};
